# Jekyll configuration for GitHub Pages

# Theme - GitHub's default
theme: jekyll-theme-primer

# Site settings
title: Aidan's Projects
description: Aidan had some thoughts...
url: "https://aidanw-98.github.io"
baseurl: "/Random-Stuff"

# Build settings
markdown: GFM
