# Jekyll configuration for GitHub Pages

# Theme
remote_theme: kitian616/jekyll-TeXt-theme

# Site settings
title: Blogs
description: A collection of thoughts and insights
baseurl: "/Random-Stuff"
url: "https://aidanw-98.github.io"
text_skin: forest
highlight_theme: tomorrow

# Plugins
plugins:
  - jekyll-gfm-admonitions
  - jekyll-remote-theme

# Build settings
markdown: GFM
